language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - master
cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - ng lint
#  - ng test
#  - ng e2e
  - ng build --prod
